routes/web.php
    Route::post('/user/buy_song', 'UserController@buySong');
    Route::post('/user/buy_album', 'UserController@buyAlbum');
    Route::get('/user/download_song/{id}', 'UserController@downloadSong');
    Route::get('/user/{album_id}/download_album/{song_id}', 'UserController@downloadSongByAlbum');

    /*
    |--------------------------------------------------------------------------
    | Payment
    |--------------------------------------------------------------------------
    */

    // Coda Pay
    Route::get('/user/payment', 'PaymentController@showPayment');
    Route::post('/payment/coda-pay', 'PaymentController@payWithCodaPay');

    // MPU
    Route::post('/payment/mpu-pay', 'PaymentController@payWithMPU');

    // Paypal
    Route::post('/payment/paypal', 'PaypalController@payWithPaypal');

    /*
    |--------------------------------------------------------------------------
    | End of Mobile Payment
    |--------------------------------------------------------------------------
*/
});


Route::get('/backend/login','Admin\AuthController@index')->name('backend.login');
Route::post('/backend/login','Admin\AuthController@loginValidate');
Route::get('/logout', 'Admin\AuthController@logout')->name('logout' );

Route::group(['middleware' => 'backendauth', 'prefix' => 'backend'], function () {

	Route::get("/dashboard/getdata", 'Admin\DashboardController@getSongData')->name('dashboard.getData');
	Route::get("/dashboard", 'Admin\DashboardController@index')->name('dashboard');

	Route::get("/", 'Admin\UserController@index');
	Route::get("users/getdata", 'Admin\UserController@getData')->name("users.getData");
	Route::resource('users','Admin\UserController');

	Route::get("members/getdata", 'Admin\MemberController@getData')->name("members.getData");
	Route::resource('members','Admin\MemberController');

	Route::get('/laravel-filemanager', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show')->name('medias');
    Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\Controllers\UploadController@upload');
	//role route

	Route::get("roles/getdata", 'Admin\RoleController@getData')->name("roles.getData");
	Route::resource('roles','Admin\RoleController');

	//artist category

	Route::get("artistcategory/getdata", 'Admin\ArtistCategoryController@getData')->name("artistcategory.getData");
	Route::resource('artistcategory','Admin\ArtistCategoryController');

	Route::get("artisttype/getdata", 'Admin\ArtistTypeController@getData')->name("artisttype.getData");
	Route::resource('artisttype','Admin\ArtistTypeController');

	Route::get("artists/getdata", 'Admin\ArtistController@getData')->name("artists.getData");
	Route::resource('artists','Admin\ArtistController');

	//music
	//Feelings
	Route::get("feelings/getdata", 'Admin\FeelingController@getData')->name("feelings.getData");
	Route::resource('feelings','Admin\FeelingController');
	//Genr category
	Route::get("songcategory/getdata", 'Admin\SongCategoryController@getData')->name("songcategory.getData");
	Route::resource('songcategory','Admin\SongCategoryController');
	//Song
	Route::get("songs/getdata", 'Admin\SongController@getData')->name("songs.getData");
	Route::resource('songs','Admin\SongController');
	//search song
	Route::post("songs/getsearchsong","Admin\SongController@getSearchSong");
	//Album
	Route::get("albums/getdata", 'Admin\AlbumController@getData')->name("albums.getData");
	Route::resource('albums','Admin\AlbumController');
	//PlayList
	Route::get("playlists/getdata", 'Admin\PlayListController@getData')->name("playlists.getData");
	Route::resource('playlists','Admin\PlayListController');

	//VideoPlayList
	Route::get("videoplaylists/getdata", 'Admin\VideoPlaylistController@getData')->name("videoplaylists.getData");
	Route::resource('videoplaylists','Admin\VideoPlaylistController');
	//AlbumList
	Route::get("albumlists/getdata", 'Admin\AlbumListController@getData')->name("albumlists.getData");
	Route::resource('albumlists','Admin\AlbumListController');
	//Price for song
	Route::get("prices/getdata", 'Admin\PriceController@getData')->name("prices.getData");
	Route::resource('prices','Admin\PriceController');

	//Price for album
	Route::get("albumprices/getdata", 'Admin\AlbumPriceController@getData')->name("albumprices.getData");
	Route::resource('albumprices','Admin\AlbumPriceController');
	// currency
	Route::get("currency","Admin\CurrencyController@create")->name('currency.create');
	Route::post("currency/store","Admin\CurrencyController@store")->name('currency.store');
	//Price for Subscription
	Route::get("subprice/getdata", 'Admin\SubscriptionPriceController@getData')->name("subprice.getData");
	Route::resource('subprice','Admin\SubscriptionPriceController');
	//Video Category
	Route::get("videocategory/getdata", 'Admin\VideoCatController@getData')->name("videocategory.getData");
	Route::resource('videocategory','Admin\VideoCatController');
	// Aggregator
	Route::get("aggregator/getdata", 'Admin\AggregatorController@getData')->name("aggregator.getData");
	Route::resource('aggregator','Admin\AggregatorController');
	//Video
	Route::get("videos/getdata", 'Admin\VideoController@getData')->name("videos.getData");
	Route::resource('videos','Admin\VideoController');

	//News Category
	Route::get("newcategory/getdata", 'Admin\NewCatController@getData')->name("newcategory.getData");
	Route::resource('newcategory','Admin\NewCatController');

	//News
	Route::get("news/getdata", 'Admin\NewsController@getData')->name("news.getData");
	Route::resource('news','Admin\NewsController');
	//Event
	Route::get("events/getdata", 'Admin\EventController@getData')->name("events.getData");
	Route::resource('events','Admin\EventController');
	//Slider
	Route::get("sliders/getdata", 'Admin\SliderController@getData')->name("sliders.getData");
	Route::resource('sliders','Admin\SliderController');

	//Song CMS
	Route::get("cms/getdata", 'Admin\CmsController@getData')->name("cms.getData");
	Route::resource('cms','Admin\CmsController');
	//video cms
	Route::get("videocms/getdata", 'Admin\VideoCmsController@getData')->name("videocms.getData");
	Route::resource('videocms','Admin\VideoCmsController');

	Route::get("video/{name}/videocms","Admin\VideoCmsController@createCms")->name('video.videocms');
	Route::post("video/videocms/storecms","Admin\VideoCmsController@storeCms")->name('video.videocms.storecms');
	//album cms
	Route::get("albumcms/getdata", 'Admin\AlbumCmsController@getData')->name("albumcms.getData");
	Route::resource('albumcms','Admin\AlbumCmsController');

	Route::get("cms/{name}/albumcms","Admin\AlbumCmsController@createCms")->name('cms.albumcms');
	Route::post("cms/albumcms/storecms","Admin\AlbumCmsController@storeCms")->name('cms.albumcms.storecms');
	//cms for playlist
	Route::get("cms/{name}/playlistcms","Admin\PlaylistCmsController@createCms")->name('cms.playlistcms');
	Route::post("cms/playlistcms/storecms","Admin\PlaylistCmsController@storeCms")->name('cms.playlistcms.storecms');
	//cms for collection
	Route::get("cms/{name}/albumlistcms","Admin\AlbumlistCmsController@createCms")->name('cms.albumlistcms');
	Route::post("cms/albumlistcms/storecms","Admin\AlbumlistCmsController@storeCms")->name('cms.albumlistcms.storecms');
	//promotions
	Route::get("promotions/getdata", 'Admin\PromotionController@getData')->name("promotions.getData");
	Route::resource('promotions','Admin\PromotionController');
	//notification
	Route::get("notification/getdata", 'Admin\NotificationController@getData')->name("notification.getData");
	Route::resource('notification','Admin\NotificationController');

	Route::get('reports/payment','Admin\ReportController@payment')->name('reports.payment');
	//for report

	Route::get('reports/getpayment','Admin\ReportController@getPaymentData')->name('report.getPaymentData');

	//for transaction
	Route::post('reports/withpayment','Admin\ReportController@wihtPayment')->name('withpayment');

	Route::get('reports/getsonglintendata','Admin\ReportController@getSongListenData')->name('reports.getSongListenData');
	//for Get song order
	Route::get('reports/getsongorderdata','Admin\ReportController@getSongOrderData')->name('reports.getSongOrderData');
	Route::get('reports/getsongorder','Admin\ReportController@getSongOrder')->name('reports.getsongorder');
	Route::post('reports/songorder','Admin\ReportController@songOrder')->name('reports.songorder');
	//for Get Album order
	Route::get('reports/getalbumorderdata','Admin\ReportController@getAlbumOrderData')->name('reports.getAlbumOrderData');
	Route::get('reports/getalbumorder','Admin\ReportController@getAlbumOrder')->name('reports.getalbumorder');
	Route::post('reports/albumorder','Admin\ReportController@albumOrder')->name('reports.albumorder');
	//for Get song listen
	Route::get('reports/getsonglinten','Admin\ReportController@getSongListen')->name('reports.getsonglisten');
	Route::post('reports/songlinten','Admin\ReportController@songListen')->name('reports.songListen');

	//for Subscribes report
	Route::get('reports/getsubscribe','Admin\ReportController@getSubscription')->name('reports.getsubscribe');
	Route::post('reports/subscribe','Admin\ReportController@subscribe')->name('reports.subscribe');

	Route::get('reports/getsubscribedata','Admin\ReportController@getSubscriptionData')->name('reports.getsubscribedata');
	//bill add manually
	Route::get("bills/getdata", 'Admin\BillController@getData')->name("bills.getData");
	Route::resource('bills','Admin\BillController');
	//
	Route::get("tracklisten/getdata", 'Admin\SongViewController@getData')->name("tracklisten.getData");
	Route::get("tracklisten","Admin\SongViewController@index")->name('tracklisten');
	//for support
	// currency
	Route::get("support","Admin\SupportController@create")->name('support.create');
	Route::post("support/store","Admin\SupportController@store")->name('support.store');

    Route::get("weekly-top","Admin\WeeklyTopController@show")->name('weekly.show');

resources/views/admin/subprice/create.blade.php
@extends('layouts.admin')

@section('content')
    

   <div class="page-title-area">
                <div class="row align-items-center">
                    <div class="col-sm-6">
                        <div class="breadcrumbs-area clearfix">
                            <h4 class="page-title pull-left">Subscription Prices</h4>
                            <ul class="breadcrumbs pull-left">
                                <li><a href="{{route('dashboard')}}">Home</a></li>
                                <li><a href="{{route('subprice.index')}}">Subscription Prices</a></li>
                                <li><span> Create</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6 clearfix">
                        <div class="user-profile pull-right">
                            @include('layouts.partial.inc')
                        </div>
                    </div>
                </div>
            </div>
            <!-- page title area end -->
            <div class="main-content-inner">
                <div class="row">
                    <div class="col-lg-6 col-ml-12">
                        <div class="row">
                            <!-- Textual inputs start -->
                            <div class="col-12 mt-5">
                                <div class="card">
                                    <div class="card-body">
                                    @if (count($errors) > 0)
                                       <div class="alert alert-danger">
                                        <ul>
                                          @foreach ($errors->all() as $error)
                                          <li>{{ $error }}</li>
                                          @endforeach
                                        </ul>
                                      </div>
                                      @endif
                                    <form method="POST" action="{{route('subprice.store')}}"  >
                                     {{ csrf_field() }}
                                        <h4 class="header-title">Create Price</h4>
                                         <div class="form-group">
                                            <label for="example-text-input" class="col-form-label">Day</label>
                                            <input class="form-control" type="text"  name="num_day" placeholder="Day">
                                        </div>
                                        <div class="form-group">
                                            <label for="example-text-input" class="col-form-label">Amount</label>
                                            <input class="form-control" type="text"  name="name" placeholder="Amount">
                                        </div>
                                       
                                        <div class="form-group">
                                            <a href="{{route('subprice.index')}}" class="btn btn-danger"><i class="fa fa-remove"></i> Cancel</a>
                                           <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Save</button>
                                        </div>
                                    </form>
                                    </div>
                                </div>
                            </div>
                            <!-- Textual inputs end -->
                           
                        </div>
                    </div>
                   
                </div>
            </div>
@endsection

resources/views/admin/subprice/edit.blade.php
@extends('layouts.admin')

@section('content')
    

   <div class="page-title-area">
                <div class="row align-items-center">
                    <div class="col-sm-6">
                        <div class="breadcrumbs-area clearfix">
                            <h4 class="page-title pull-left">Subscription Prices</h4>
                            <ul class="breadcrumbs pull-left">
                                <li><a href="{{route('dashboard')}}">Home</a></li>
                                <li><a href="{{route('subprice.index')}}">Subscription Prices</a></li>
                                <li><span> Edit</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6 clearfix">
                        <div class="user-profile pull-right">
                            @include('layouts.partial.inc')
                        </div>
                    </div>
                </div>
            </div>
            <!-- page title area end -->
            <div class="main-content-inner">
                <div class="row">
                    <div class="col-lg-6 col-ml-12">
                        <div class="row">
                            <!-- Textual inputs start -->
                            <div class="col-12 mt-5">
                                <div class="card">
                                    <div class="card-body">
                                    @if (count($errors) > 0)
                                       <div class="alert alert-danger">
                                        <ul>
                                          @foreach ($errors->all() as $error)
                                          <li>{{ $error }}</li>
                                          @endforeach
                                        </ul>
                                      </div>
                                      @endif
                                    <form method="POST" action="{{route('subprice.update',$subprice->id)}}"  >
                                     {{ csrf_field() }}
                                        <h4 class="header-title">Update Price</h4>
                                         <div class="form-group">
                                            <label for="example-text-input" class="col-form-label">Day</label>
                                            <input class="form-control" type="text"  name="num_day" value="{{$subprice->num_day}}" placeholder="Day">
                                        </div>
                                        <div class="form-group">
                                            <label for="example-text-input" class="col-form-label">Amount</label>
                                            <input class="form-control" type="text"  name="name" value="{{$subprice->name}}" placeholder="Amount">
                                        </div>
                                      
                                       <form action="{{ route('subprice.store', $subprice->id) }}"
                                    >
                                        {{ csrf_field() }}
                                        {{ method_field("patch") }}
                                         <div class="form-group">
                                            <a href="{{route('subprice.index')}}" class="btn btn-danger"><i class="fa fa-remove"></i> Cancel</a>
                                           <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Save</button>
                                        </div>
                                    </form>
                                    </form>
                                    </div>
                                </div>
                            </div>
                            <!-- Textual inputs end -->
                           
                        </div>
                    </div>
                   
                </div>
            </div>
@endsection

resources/views/admin/subprice/index.blade.php
@extends('layouts.admin')

@section('content')
    
  <div class="page-title-area">
                <div class="row align-items-center">
                    <div class="col-sm-6">
                        <div class="breadcrumbs-area clearfix">
                            <h4 class="page-title pull-left">Subscription Price</h4>
                            <ul class="breadcrumbs pull-left">
                                <li><a href="{{route('dashboard')}}">Home</a></li>
                                <li>Subscription Price</li>
                                
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6 clearfix">
                        <div class="user-profile pull-right">
                            @include('layouts.partial.inc')
                        </div>
                    </div>
                </div>
            </div>
            <!-- page title area end -->
            <div class="main-content-inner">
                <div class="row">
                    <!-- data table start -->
                    <div class="col-8 mt-3" ></div>
                    <div class="col-4 mt-3">
                        @if (Session::has('message'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ Session::get('message') }}
                            </div>
                        @endif
                    </div>
                    <div class="col-12 mt-5">
                        <div class="card">
                            <div class="card-body">
                            
                            <p class="pull-right"><a href="{{route('subprice.create')}}" class="btn btn-primary"><i class="fa fa-plus"></i> Add</a></p>
                            
                                <h4 class="header-title">Subscription Price List</h4>
                                
                                <div class="data-tables">
                                    <table id="subpriceTable" class="text-center">
                                        <thead class="bg-light text-capitalize">
                                            <tr>
                                                <th>No</th>
                                                <th>Day</th>
                                                <th>Amount</th>
                                               <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                       
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- data table end -->
                   
                </div>
            </div>

            
@endsection


@push('scripts')
<script>
$(function() {
    var baseUrl = '{!! URL::to("/") !!}';
  let me = this;
     this.tbl = $('#subpriceTable').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('subprice.getData') !!}',
        columns: [
            { data: 'no', orderable: false, bSearchable: false },
            { data: 'num_day', name: 'num_day' },
            { data: 'name', name: 'name' },
            {data: 'action', name: 'action', orderable: false, searchable: false},
            
        ],
        "fnRowCallback" : function(nRow, aData, iDisplayIndex){
          // For auto numbering at 'No' column
          var start = me.tbl.page.info().start;
          $('td:eq(0)',nRow).html(start + iDisplayIndex + 1);
      }
    });

  

   $('#subpriceTable').on('click', '.sub-delete', function(e) {
    e.preventDefault();
    var id = $(this).data('id');
    var checked = confirm("Sure You want to delete it");
    if(checked){
        $.ajax({
          headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          },
          type : "DELETE",
          url  : baseUrl + '/backend/subprice/' + id,
          data : {},
          success: function(data){
            var result = $.parseJSON(data);
            if(result['status'] == 'success'){
                me.tbl.ajax.reload( null, false );
            }else{
                alert(result['message']);        
            }
        },
          error: function(XMLHttpRequest, textStatus, errorThrown) {
            alert('Error in student view. Please contact to administrator');
          }
        });  
    }else{
        return false;
    }
        
  });
    
});
  

</script>
@endpush