routes/web.php
    $full_file = 'https://s3-ap-southeast-1.amazonaws.com/mmn01/Music/Maung+Maung_%E1%80%B1%E1%80%9B%E1%80%81%E1%80%BA%E1%80%AD%E1%80%B3%E1%80%B8%E1%80%81%E1%80%B2%E1%82%94%E1%80%95%E1%80%AB/05+Ngar+Ma+Thi+Tae+Thi+Chin+Myar+(%E1%80%84%E1%80%AB%E1%80%99%E1%80%9E%E1%80%AD%E1%80%90%E1%80%B2%E1%82%94%E1%80%9E%E1%80%AE%E1%80%81%E1%80%BA%E1%80%84%E1%80%B9%E1%80%B8%E1%80%99%E1%80%BA%E1%80%AC%E1%80%B8).mp3';
    $filename = basename($full_file);

    return response()->streamDownload(function () use ($full_file){
        echo file_get_contents($full_file);
    }, $filename,[
        'Pragma' => 'public',
        'Expires' => 0,
        'Cache-Control' => 'must-revalidate, post-check=0, pre-check=0',
        'Cache-Control' => 'public',
        'Content-Description' => 'File Transfer',
        'Content-Type' => 'application/octet-stream',
        'Content-Disposition' => 'attachment; filename="'.$filename.'"',
        'Content-Transfer-Encoding' => 'binary'
    ]);
});

// Social Login
Route::get('auth/{provider}', 'SocialController@getSocialRedirect');
Route::get('auth/{provider}/callback', 'SocialController@getSocialHandle');

Route::get('/', 'PagesController@index');
Route::get('/home', 'PagesController@index')->name('home');

Route::get('/new-releases', 'PagesController@newReleases');
Route::get('/top-albums', 'PagesController@topAlbums');
Route::get('/recommended-playlist', 'PagesController@recommendedPlaylist');

Route::get('/album/{id}', 'PagesController@album');
Route::get('/albums', 'PagesController@albums');
Route::get('/music/all_free_music', 'PagesController@freeMusic');
Route::get('/music/top_tracks', 'PagesController@topSongs');

Route::get('/collections', 'PagesController@showCollectionList');
Route::get('/collection/{id}', 'PagesController@showCollection');

Route::get('/artist/{id}', 'PagesController@artist');
Route::get('/artists', 'PagesController@artists');
Route::get('/artists/{id}/{slug}', 'PagesController@artistsByCategory');

Route::get('/genres','PagesController@genres');
Route::get('/genre/{genre}','PagesController@genre');

Route::get('/feelings','PagesController@feelings');
Route::get('/feeling/{feeling}','PagesController@feeling');

Route::get('/playlist','PagesController@playlist');
Route::get('/playlist/{id}','PagesController@playlistDetail');

Route::get('search', 'SearchController@showAll');

Route::get('/search-by-song', 'SearchController@bySong');
Route::get('/search-by-artist', 'SearchController@byArtist');
Route::get('/search-by-album', 'SearchController@byAlbum');
Route::get('/search-by-playlist', 'SearchController@byPlaylist');

Route::get('/videos', 'PagesController@videos');
Route::get('/video/{id}', 'PagesController@video');
Route::get('/videos/{id}/{slug}', 'PagesController@videosByCategory');

Route::post('/song_play/{id}', 'ClickCountAndRecentController@create');
Route::get('/download_free_song/{id}', 'PagesController@downloadFreeSong');

Route::get('/events', 'PagesController@events');
Route::get('/event/{id}', 'PagesController@event');

Route::get('/privacy_policy', 'PagesController@privacy');

Route::get('support_guide','PagesController@supportGuide');

/*
|--------------------------------------------------------------------------
| For Mobile Payment And Payment Gateway
|--------------------------------------------------------------------------
*/

/*
 * require user_id and amount
 */
Route::get('/mobile/coda-pay', 'PaymentMobileController@showCodaPayPayment');

/*
 * require user_id and amount.
 */
Route::post('/mobile/mpu-pay', 'PaymentMobileController@payWithMPU');
Route::get('/mobile/mpu-pay', 'PaymentMobileController@showMpuPayPayment');

/*
 * require user_id and amount.
 */
Route::post('/mobile/paypal', 'PaypalMobileController@payWithPaypal');
Route::get('/mobile/paypal', 'PaymentMobileController@showPayPal');


Route::get('/transaction_success','PaymentMobileController@transactionSuccess');
Route::get('/transaction_failed','PaymentMobileController@transactionFailed');

/*
 * Payment Gateway callback.
 */
Route::get('/payment/paypal-response', 'PaypalController@getPaymentStatus');

Route::get('/coda-response', 'HandelPaymentRespondController@codaResponse');

Route::post('/mpu_front', 'HandelPaymentRespondController@getMPUFrondEndRespond');
Route::post('/mpu_back', 'HandelPaymentRespondController@getMPUBackEndRespond');

/*
|--------------------------------------------------------------------------
| End of Mobile Payment And Payment Gateway
|--------------------------------------------------------------------------
*/

Route::middleware(['verified','auth'])->group(function() {
    Route::post('/favourite/song/{id}', 'UserController@favouriteSong');
    Route::post('/favourite/album/{uuid}', 'UserController@favouriteAlbum');

    Route::post('/like/album/{uuid}', 'UserController@likeAlbum');

    Route::delete('/favourite/song/{id}', 'UserController@deleteFavouriteSong');
    Route::delete('/favourite/album/{uuid}', 'UserController@deleteFavouriteAlbum');


    Route::get('/user/profile','UserController@profile');
    Route::get('/account/edit_account_info','UserController@showProfileEditPage');
    Route::post('/account/edit_account_info','UserController@editProfile');
    Route::get('/account/change_password','UserController@showChangePasswordPage');
    Route::post('/password/change','UserController@passwordChange')->name('user.password.change');

    Route::get('/user/favourite','UserController@showUserFav');

    Route::get('/mymusic/favourite_songs','UserController@showUserFavSongs');
    Route::get('/mymusic/favourite_albums','UserController@showUserFavAlbums');

    Route::get('/user/purchased','UserController@purchasedPage');
    Route::get('/mymusic/purchased_songs','UserController@showUserPurchasedSongs');
    Route::get('/mymusic/purchased_albums','UserController@showUserPurchasedAlbums');
    Route::get('/mymusic/purchased_album/{id}','UserController@showUserPurchasedAlbum');

    Route::get('/recent','UserController@showRecentPage');

    Route::post('/user/subscribe','UserController@subscribe');
    Route::post('/user/streaming_quality','UserController@updateStreamingQuality');

    Route::post('/user/buy_song', 'UserController@buySong');
    Route::post('/user/buy_album', 'UserController@buyAlbum');
    Route::get('/user/download_song/{id}', 'UserController@downloadSong');
    Route::get('/user/{album_id}/download_album/{song_id}', 'UserController@downloadSongByAlbum');

    /*
    |--------------------------------------------------------------------------
    | Payment
    |--------------------------------------------------------------------------
    */

    // Coda Pay
    Route::get('/user/payment', 'PaymentController@showPayment');
    Route::post('/payment/coda-pay', 'PaymentController@payWithCodaPay');

    // MPU
    Route::post('/payment/mpu-pay', 'PaymentController@payWithMPU');

    // Paypal
    Route::post('/payment/paypal', 'PaypalController@payWithPaypal');

    /*
    |--------------------------------------------------------------------------
    | End of Mobile Payment
    |--------------------------------------------------------------------------
*/
});


Route::get('/backend/login','Admin\AuthController@index')->name('backend.login');
Route::post('/backend/login','Admin\AuthController@loginValidate');
Route::get('/logout', 'Admin\AuthController@logout')->name('logout' );

Route::group(['middleware' => 'backendauth', 'prefix' => 'backend'], function () {

	Route::get("/dashboard/getdata", 'Admin\DashboardController@getSongData')->name('dashboard.getData');
	Route::get("/dashboard", 'Admin\DashboardController@index')->name('dashboard');

	Route::get("/", 'Admin\UserController@index');
	Route::get("users/getdata", 'Admin\UserController@getData')->name("users.getData");
	Route::resource('users','Admin\UserController');

	Route::get("members/getdata", 'Admin\MemberController@getData')->name("members.getData");
	Route::resource('members','Admin\MemberController');

	Route::get('/laravel-filemanager', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show')->name('medias');
    Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\Controllers\UploadController@upload');
	//role route

	Route::get("roles/getdata", 'Admin\RoleController@getData')->name("roles.getData");
	Route::resource('roles','Admin\RoleController');

	//artist category

	Route::get("artistcategory/getdata", 'Admin\ArtistCategoryController@getData')->name("artistcategory.getData");
	Route::resource('artistcategory','Admin\ArtistCategoryController');

	Route::get("artisttype/getdata", 'Admin\ArtistTypeController@getData')->name("artisttype.getData");
	Route::resource('artisttype','Admin\ArtistTypeController');

	Route::get("artists/getdata", 'Admin\ArtistController@getData')->name("artists.getData");
	Route::resource('artists','Admin\ArtistController');

	//music
	//Feelings
	Route::get("feelings/getdata", 'Admin\FeelingController@getData')->name("feelings.getData");
	Route::resource('feelings','Admin\FeelingController');
	//Genr category
	Route::get("songcategory/getdata", 'Admin\SongCategoryController@getData')->name("songcategory.getData");
	Route::resource('songcategory','Admin\SongCategoryController');
	//Song
	Route::get("songs/getdata", 'Admin\SongController@getData')->name("songs.getData");
	Route::resource('songs','Admin\SongController');
	//search song
	Route::post("songs/getsearchsong","Admin\SongController@getSearchSong");
	//Album
	Route::get("albums/getdata", 'Admin\AlbumController@getData')->name("albums.getData");
	Route::resource('albums','Admin\AlbumController');
	//PlayList
	Route::get("playlists/getdata", 'Admin\PlayListController@getData')->name("playlists.getData");
	Route::resource('playlists','Admin\PlayListController');

	//VideoPlayList
	Route::get("videoplaylists/getdata", 'Admin\VideoPlaylistController@getData')->name("videoplaylists.getData");
	Route::resource('videoplaylists','Admin\VideoPlaylistController');

app/User.php
<?php

namespace App;

use App\Payment\Subscribable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Laravel\Passport\HasApiTokens;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;
    use HasApiTokens;
    use LaratrustUserTrait;
    use Subscribable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'phone', 'email_verified_at', 'remained_amount', 'streaming_quality'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function recent_songs() {
        return $this->belongsToMany(Song::class, 'recents',
            'user_id', 'song_id');
    }

    public function songs() {
        return $this->belongsToMany(Song::class, 'orders','user_id', 'item_id')
                    ->where('type', 'song')->withTimestamps();
    }

    public function albums() {
        return $this->belongsToMany(Album::class, 'orders','user_id', 'item_id')
            ->where('type', 'album')->withTimestamps();
    }

    public function favourite_songs() {
        return $this->belongsToMany(Song::class, 'favourites',
            'user_id', 'item_id')->where('type', 'song')->withTimestamps();
    }

    public function favourite_albums() {
        return $this->belongsToMany(Album::class, 'favourites',
            'user_id', 'item_id')->where('type', 'album')->withTimestamps();
    }

    public function like_albums() {
        return $this->belongsToMany(Album::class, 'album_likes',
            'user_id', 'album_id')->withTimestamps();
    }


    public function comments() 
    {
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;


use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Role;
use App\Permission;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\StoreUser;
use App\Http\Requests\UpdateUser;
use Yajra\Datatables\Datatables;
use DB;
use Session;
class UserController extends Controller
{
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct() {
        $this->middleware("auth");
       
    }
  
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       
        return view('admin.user.index');
    }

    public function getData()
    {
        $user = User::whereHas('roles', function($q){
            $q->where('name', 'admin');
        })->get();
        $table = DataTables::of($user)
            ->escapeColumns([])
            ->addColumn('no', function ($user) {
                return '';
            })
            
            ->addColumn('action', function ($user) {
               

                $btn = '<a href="'. route('users.edit', $user) .'" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i></a>';

                $btn .= '<a href="#" data-id="'.$user->id.'" class="btn btn-danger btn-sm sub-delete"><i class="fa fa-remove"></i></a>';
               
                return "<div class='action-column'>" . $btn . "</div>";
            });

        return $table->make(true);
    }


    public function create()
    {

        $roles = Role::get();        
        return view('admin.user.create',compact('roles'));
    }
    public function store(Request $request)
    {
        
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:6|confirmed',
            'roles' => 'required'
        ]);

        $input['password'] = bcrypt($request->get('password'));
        $input['name'] = $request->get('name');
        $input['email'] = $request->get('email');
        $user = User::create($input);
        
        if($request->roles <> ''){
            $user->roles()->attach($request->roles);
        }
        Session::flash('message', 'You have successfully Insert User.');
        return redirect()->route('users.index');            
        
    }
    public function edit($id) {
        $user = User::findOrFail($id);
       
        $roles = Role::get(); 
        return view('admin.user.edit', compact('user', 'roles','userRole')); 
    }
    public function update(UpdateUser $request, $id) {
        $user = User::findOrFail($id);   
        $this->validate($request, [
            
            'password'=>'confirmed'
        ]);
        $input = $request->except('roles');
        
         $name  = $request->input("name");
        $email     = $request->input('email');
        $password  = $request->input('password');
        
        if(isset($password) && !empty($password)){
            $userupdate = ['name' => $name,'email' => $email,'password'=>bcrypt($password)];

        }else{
             $userupdate = ['name' => $name,'email' => $email];
        }
       
       DB::table('users')
            ->where('id', $id)
            ->update($userupdate);
        if ($request->roles <> '') {
            $user->roles()->sync($request->roles);        
        }        
        else {
            $user->roles()->detach(); 
        }
        Session::flash('message', 'You have successfully Update User.');
        return redirect()->route('users.index');
    }
    public function destroy($id) {
        $user = User::findOrFail($id); 
        $user->delete();
        if($user){
            $data = [
            'status' => "success",
            'message' => "Delete Success"
            ];
        }else{
            $data = [
            'status' => "fail",
            'message' => "Sorry can't delete "
            ];
        }
        return json_encode($data);
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.admin')

@section('content')
    

   <div class="page-title-area">
                <div class="row align-items-center">
                    <div class="col-sm-6">
                        <div class="breadcrumbs-area clearfix">
                            <h4 class="page-title pull-left">User</h4>
                            <ul class="breadcrumbs pull-left">
                                <li><a href="{{route('dashboard')}}">Home</a></li>
                                <li><span>Form</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6 clearfix">
                        <div class="user-profile pull-right">
                            @include('layouts.partial.inc')
                        </div>
                    </div>
                </div>
            </div>
            <!-- page title area end -->
            <div class="main-content-inner">
                <div class="row">
                    <div class="col-lg-6 col-ml-12">
                        <div class="row">
                            <!-- Textual inputs start -->
                            <div class="col-12 mt-5">
                                <div class="card">
                                    <div class="card-body">
                                    @if (count($errors) > 0)
                                       <div class="alert alert-danger">
                                        <ul>
                                          @foreach ($errors->all() as $error)
                                          <li>{{ $error }}</li>
                                          @endforeach
                                        </ul>
                                      </div>
                                      @endif
                                    <form method="POST" action="{{route('users.store')}}"  >
                                     {{ csrf_field() }}
                                        <h4 class="header-title">Create User</h4>
                                        
                                        <div class="form-group">
                                            <label for="example-text-input" class="col-form-label">Name</label>
                                            <input class="form-control" type="text"  name="name" placeholder="Name">
                                        </div>
                                        <div class="form-group">
                                            <label for="example-search-input" class="col-form-label">Email</label>
                                            <input class="form-control" type="email"  name="email" placeholder="Email">
                                        </div>
                                        <div class="form-group">
                                            <label for="example-email-input" class="col-form-label">Password</label>
                                            <input class="form-control" type="password"  name="password" placeholder="Password">
                                        </div>
                                        
                                        <div class="form-group">
                                            <label for="inputPassword" class="">Confirm Password</label>
                                            <input type="password" class="form-control" name="password_confirmation"  placeholder="Confirm Password">
                                        </div>
                                        <div class="form-group">
                                            @foreach ($roles as $role)
                                                {!! Form::checkbox('roles[]',  $role->id ) !!}
                                                {!! Form::label($role->name, ucfirst($role->name)) !!}<br>
                                            @endforeach
                                        </div>
                                        <div class="form-group">
                                            <a href="{{route('users.index')}}" class="btn btn-danger"><i class="fa fa-remove"></i> Cancel</a>
                                           <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Save</button>
                                        </div>
                                    </form>
                                    </div>
                                </div>
                            </div>
                            <!-- Textual inputs end -->
                           
                        </div>
                    </div>
                   
                </div>
            </div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.admin')

@section('content')
    

   <div class="page-title-area">
                <div class="row align-items-center">
                    <div class="col-sm-6">
                        <div class="breadcrumbs-area clearfix">
                            <h4 class="page-title pull-left">User</h4>
                            <ul class="breadcrumbs pull-left">
                                <li><a href="{{route('dashboard')}}">Home</a></li>
                                <li><span>Form</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6 clearfix">
                        <div class="user-profile pull-right">
                            @include('layouts.partial.inc')
                        </div>
                    </div>
                </div>
            </div>
            <!-- page title area end -->
            <div class="main-content-inner">
                <div class="row">
                    <div class="col-lg-6 col-ml-12">
                        <div class="row">
                            <!-- Textual inputs start -->
                            <div class="col-12 mt-5">
                                <div class="card">
                                    <div class="card-body">
                                    @if (count($errors) > 0)
                                       <div class="alert alert-danger">
                                        <ul>
                                          @foreach ($errors->all() as $error)
                                          <li>{{ $error }}</li>
                                          @endforeach
                                        </ul>
                                      </div>
                                      @endif
                                    <form method="POST" action="{{route('users.update',$user->id)}}"  >
                                     {{ csrf_field() }}
                                        <h4 class="header-title">Update User</h4>
                                        
                                        <div class="form-group">
                                            <label for="example-text-input" class="col-form-label">Name</label>
                                            <input class="form-control" type="text"  name="name" value="{{$user->name}}" placeholder="Name">
                                        </div>
                                        <div class="form-group">
                                            <label for="example-search-input" class="col-form-label">Email</label>
                                            <input class="form-control" type="email"  name="email" value="{{$user->email}}" placeholder="Email">
                                        </div>
                                        <div class="form-group">
                                            <label for="example-email-input" class="col-form-label">Password</label>
                                            <input class="form-control" type="password"  name="password" placeholder="Password">
                                        </div>
                                        
                                        <div class="form-group">
                                            <label for="inputPassword" class="">Confirm Password</label>
                                            <input type="password" class="form-control" name="password_confirmation"  placeholder="Confirm Password">
                                        </div>
                                        <div class="form-group">
                                        @foreach ($roles as $r)
                                            <label >
                                                <input type="checkbox"  name="roles[]" value="{{$r->id}}" {{ $user->roles->contains($r->id) ? 'checked' : '' }}> {{ucfirst($r->name)}}
                                            </label><br />
                                            @endforeach
                                        </div>
                                       <form action="{{ route('users.store', $user->id) }}"
                                    >
                                        {{ csrf_field() }}
                                        {{ method_field("patch") }}
                                         <div class="form-group">
                                            <a href="{{route('users.index')}}" class="btn btn-danger"><i class="fa fa-remove"></i> Cancel</a>
                                           <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Save</button>
                                        </div>
                                    </form>
                                    </form>
                                    </div>
                                </div>
                            </div>
                            <!-- Textual inputs end -->
                           
                        </div>
                    </div>
                   
                </div>
            </div>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.admin')

@section('content')
    
  <div class="page-title-area">
                <div class="row align-items-center">
                    <div class="col-sm-6">
                        <div class="breadcrumbs-area clearfix">
                            <h4 class="page-title pull-left">User</h4>
                            <ul class="breadcrumbs pull-left">
                                <li><a href="{{route('dashboard')}}">Home</a></li>
                                <li><span>User</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6 clearfix">
                        <div class="user-profile pull-right">
                            @include('layouts.partial.inc')
                        </div>
                    </div>
                </div>
            </div>
            <!-- page title area end -->
            <div class="main-content-inner">
                <div class="row">
                    <!-- data table start -->
                    <div class="col-8 mt-3" ></div>
                    <div class="col-4 mt-3">
                        @if (Session::has('message'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ Session::get('message') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <i class="fa fa-remove"></i>
                                </button>
                            </div>
                        @endif
                    </div>
                    <div class="col-12 mt-5">
                        <div class="card">
                            <div class="card-body">
                            @if(Auth::user()->hasRole('admin'))
                            <p class="pull-right"><a href="{{route('users.create')}}" class="btn btn-primary"><i class="fa fa-plus"></i> Add</a></p>
                            @endif
                                <h4 class="header-title">User List</h4>
                                
                                <div class="data-tables">
                                    <table id="userTable" class="text-center">
                                        <thead class="bg-light text-capitalize">
                                            <tr>
                                                <th>ID</th>
                                                <th>Name</th>
                                                <th>Email</th>
                                                <th>Phone</th>
                                               <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                       
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- data table end -->
                   
                </div>
            </div>
@endsection


@push('scripts')
<script>
$(function() {
    var baseUrl = '{!! URL::to("/") !!}';
  let me = this;
     this.tbl = $('#userTable').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('users.getData') !!}',
        columns: [
            { data: 'id', name:'id'  },
            { data: 'name', name: 'name' },
            { data: 'email', name: 'email' },
            { data: 'phone', name: 'phone' },
            {data: 'action', name: 'action', orderable: false, searchable: false},
            
        ],
        
    });

  
    $('#userTable').on('click', '.sub-delete', function(e) {
    e.preventDefault();
    var id = $(this).data('id');
    var checked = confirm("Sure You want to delete it");
    if(checked){
        $.ajax({
          headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          },
          type : "DELETE",
          url  : baseUrl + '/backend/users/' + id,
          data : {},
          success: function(data){
            var result = $.parseJSON(data);
            if(result['status'] == 'success'){
                me.tbl.ajax.reload( null, false );
            }else{
                alert(result['message']);        
            }
        },
          error: function(XMLHttpRequest, textStatus, errorThrown) {
            alert('Error in student view. Please contact to administrator');
          }
        });  
    }else{
        return false;
    }
        
  });
   
});
  

</script>
@endpush